export const sliceName = {
  authSlice: 'auth-slice',
  taskSlice: 'task-slice',
  inboxSlice: 'inbox-slice',
  contactsSlice: 'contacts-slice',
  contactScheduleSlice: 'contact-schedules-slice',
  aboutContactSlice: 'about-contact-slice',
  contactNoteSlice: 'contact-note-slice',
  contactTaskSlice: 'contact-task-slice',
  userSlice: 'user-slice',
  eachMessageSlice: 'each-message-slice',
  contactDetailsSlice: 'contact-details',
  userTagsSlice: 'user-tags',
  campaignFolderSlice: 'campaign-folders',
  campaignsSlice: 'campaigns',
  dealStagesSlice: 'deals',
  pipeline: 'deal-folders',
  dashboardSlice: 'dashboard-slice',
  bottomSheetSlice: 'bottomSheet-slice',
  callSlice: 'call-slice',
  callHistorySlice: 'call-history-slice',
  quickReplySlice: 'quick-reply-slice',
};
