export const config = {
  frontEndUrl: 'https://app.pypepro.com/api/v3',
  backEndUrl: 'https://mobile-api.pypepro.io/mv3',
  agencyId: 56,
  privacyUrl: 'https://app.kindcrm.com/privacy-policy',
  termsUrl: 'https://app.kindcrm.com/terms-and-conditions',
  title: 'KindCRM',
  environment: 'production',
  activityHeight: 0,
  apiTimeout: 60 * 1000,
  currencySymbol: '$',
  firebase:
    'AAAAzHjZq5Y:APA91bEqTDl8aZIraVoBZ7k-qY_FwCgBc5oq9KKrMDkUyvfthk4L14UEwkluTFaBVrZAnJbzn05l_CkknjFhZ6QtrO496nq4zF8F18lqsyJafU_va-z6mnDIxQxtPllnNo2jeclJTtB0',
  deviceType: 'android',
  localStorageDay: 5,
  webUrl: 'https://kindcrm.pypepro.com/',
  agencyName: '',
  agencyNumber: '',
  agencyEmail: '',
  commonApp: true,
  extraFeature: false,
  appColors: {
    // primary: '#006DF5',
    primary: '#51558F',
    secondary: '#F4F4F4',
    badgeColor: '#E8191C',
    // splashBg: '#1847D6',
    splashBg: '#252d47',
    splashText: '#fff',
    drawer: {},
  },
};
export const features = {
  pipeline: false,
  campaign: false,
  task: false,
  contact: false,
  inbox: false,
  userTimeline: false,
  contactTimeline: false,
  keyboard: false,
  conversation: false,
};

/* logo image dimension: 236 * 45 */
